window.DATA = {
 "phases": [
  "Lane (0-10m)",
  "Mid (10-20m)",
  "Late (20-30m)",
  "Very late (30m+)"
 ],
 "builds": [
  {
   "hero": "Ivy",
   "hero_id": 20,
   "archetype": "Spirit Ivy",
   "share": 0.33579119850187267,
   "win_rate": 0.5566399442314395,
   "n": 2869,
   "items": [
    {
     "id": 1009965641,
     "name": "Monster Rounds",
     "cost": 800,
     "phase": 0,
     "time": 70.0,
     "p": 0.23,
     "n": 2479,
     "builds_into": null,
     "into_keeps_imbue": false,
     "sold_unresolved": false,
     "stat": "+25% Weapon Damage vs. NPCs",
     "imbue": null
    },
    {
     "id": 3776945997,
     "name": "Extra Charge",
     "cost": 800,
     "phase": 0,
     "time": 191.0,
     "p": 0.389,
     "n": 318,
     "builds_into": "Rapid Recharge",
     "into_keeps_imbue": false,
     "sold_unresolved": false,
     "stat": "+1 Bonus Ability Charges",
     "imbue": null
    },
    {
     "id": 754480263,
     "name": "Mystic Expansion",
     "cost": 800,
     "phase": 0,
     "time": 304.0,
     "p": 0.23,
     "n": 96,
     "builds_into": "Greater Expansion",
     "into_keeps_imbue": false,
     "sold_unresolved": false,
     "stat": "+20% Ability Range",
     "imbue": {
      "ability": "Stone Form",
      "ability_id": 3642273386,
      "share": 0.51,
      "n": 2464,
      "split": false
     }
    },
    {
     "id": 3399065363,
     "name": "Sprint Boots",
     "cost": 800,
     "phase": 0,
     "time": 420.0,
     "p": 0.292,
     "n": 241,
     "builds_into": "Trophy Collector",
     "into_keeps_imbue": false,
     "sold_unresolved": false,
     "stat": "+2.0mm Sprint Speed",
     "imbue": null
    },
    {
     "id": 3074274290,
     "name": "Trophy Collector",
     "cost": 1600,
     "phase": 0,
     "time": 527.0,
     "p": 0.962,
     "n": 130,
     "builds_into": null,
     "into_keeps_imbue": false,
     "sold_unresolved": false,
     "stat": "+0.15mm Sprint Speed",
     "imbue": null
    },
    {
     "id": 380806748,
     "name": "Compress Cooldown",
     "cost": 1600,
     "phase": 1,
     "time": 629.0,
     "p": 0.119,
     "n": 554,
     "builds_into": "Superior Cooldown",
     "into_keeps_imbue": false,
     "sold_unresolved": false,
     "stat": "+18% Ability Cooldown Reduction",
     "imbue": {
      "ability": "Entangling Thorns",
      "ability_id": 4111222521,
      "share": 0.35,
      "n": 1602,
      "split": true
     }
    },
    {
     "id": 1813726886,
     "name": "Slowing Hex",
     "cost": 1600,
     "phase": 1,
     "time": 731.0,
     "p": 0.47,
     "n": 77,
     "builds_into": null,
     "into_keeps_imbue": false,
     "sold_unresolved": false,
     "stat": "+20% Move Speed",
     "imbue": null
    },
    {
     "id": 2603935618,
     "name": "Healbane",
     "cost": 1600,
     "phase": 1,
     "time": 838.0,
     "p": 0.261,
     "n": 22,
     "builds_into": null,
     "into_keeps_imbue": false,
     "sold_unresolved": false,
     "stat": "+7 Spirit Power",
     "imbue": null
    },
    {
     "id": 395944548,
     "name": "Torment Pulse",
     "cost": 3200,
     "phase": 1,
     "time": 950.0,
     "p": 0.207,
     "n": 26,
     "builds_into": null,
     "into_keeps_imbue": false,
     "sold_unresolved": false,
     "stat": "+25 Pulse Damage",
     "imbue": null
    },
    {
     "id": 1925087134,
     "name": "Suppressor",
     "cost": 1600,
     "phase": 1,
     "time": 1065.0,
     "p": 0.335,
     "n": 68,
     "builds_into": null,
     "into_keeps_imbue": false,
     "sold_unresolved": false,
     "stat": "+28% Fire Rate",
     "imbue": null
    },
    {
     "id": 630839635,
     "name": "Echo Shard",
     "cost": 6400,
     "phase": 1,
     "time": 1194.0,
     "p": 0.335,
     "n": 17,
     "builds_into": null,
     "into_keeps_imbue": false,
     "sold_unresolved": false,
     "stat": "Reset the cooldown of the imbued non-ultimate ability.",
     "imbue": {
      "ability": "Stone Form",
      "ability_id": 3642273386,
      "share": 0.994,
      "n": 1209,
      "split": false
     }
    },
    {
     "id": 1193964439,
     "name": "Greater Expansion",
     "cost": 3200,
     "phase": 2,
     "time": 1318.0,
     "p": 0.023,
     "n": 710,
     "builds_into": null,
     "into_keeps_imbue": false,
     "sold_unresolved": false,
     "stat": "+30% Ability Range",
     "imbue": null
    },
    {
     "id": 787198704,
     "name": "Rapid Recharge",
     "cost": 3200,
     "phase": 2,
     "time": 1441.0,
     "p": 0.229,
     "n": 38,
     "builds_into": null,
     "into_keeps_imbue": false,
     "sold_unresolved": false,
     "stat": "+2 Bonus Ability Charges",
     "imbue": null
    },
    {
     "id": 3261353684,
     "name": "Superior Cooldown",
     "cost": 3200,
     "phase": 2,
     "time": 1570.0,
     "p": 0.16,
     "n": 206,
     "builds_into": null,
     "into_keeps_imbue": false,
     "sold_unresolved": false,
     "stat": "+20% Ability Cooldown Reduction",
     "imbue": null
    },
    {
     "id": 2081037738,
     "name": "Mystic Vulnerability",
     "cost": 1600,
     "phase": 2,
     "time": 1684.0,
     "p": 0.158,
     "n": 92,
     "builds_into": "Escalating Exposure",
     "into_keeps_imbue": false,
     "sold_unresolved": false,
     "stat": "-8% Spirit Resist",
     "imbue": null
    },
    {
     "id": 3005970438,
     "name": "Escalating Exposure",
     "cost": 6400,
     "phase": 2,
     "time": 1795.0,
     "p": 0.354,
     "n": 34,
     "builds_into": null,
     "into_keeps_imbue": false,
     "sold_unresolved": false,
     "stat": "+4.5% Spirit Amp per Stack",
     "imbue": null
    },
    {
     "id": 343572757,
     "name": "Spirit Burn",
     "cost": 6400,
     "phase": 3,
     "time": 1910.0,
     "p": 0.116,
     "n": 185,
     "builds_into": null,
     "into_keeps_imbue": false,
     "sold_unresolved": false,
     "stat": "+500 Damage Threshold",
     "imbue": null
    }
   ]
  },
  {
   "hero": "Paradox",
   "hero_id": 10,
   "archetype": "Spirit Paradox",
   "share": 0.13683083511777303,
   "win_rate": 0.4859154929577465,
   "n": 1278,
   "items": [
    {
     "id": 1009965641,
     "name": "Monster Rounds",
     "cost": 800,
     "phase": 0,
     "time": 70.0,
     "p": 0.282,
     "n": 1231,
     "builds_into": null,
     "into_keeps_imbue": false,
     "sold_unresolved": false,
     "stat": "+25% Weapon Damage vs. NPCs",
     "imbue": null
    },
    {
     "id": 3399065363,
     "name": "Sprint Boots",
     "cost": 800,
     "phase": 0,
     "time": 191.0,
     "p": 0.474,
     "n": 334,
     "builds_into": "Veil Walker",
     "into_keeps_imbue": false,
     "sold_unresolved": false,
     "stat": "+2.0mm Sprint Speed",
     "imbue": null
    },
    {
     "id": 4139877411,
     "name": "Extra Stamina",
     "cost": 800,
     "phase": 0,
     "time": 304.0,
     "p": 0.545,
     "n": 74,
     "builds_into": "Arcane Surge",
     "into_keeps_imbue": false,
     "sold_unresolved": false,
     "stat": "+1 Stamina",
     "imbue": null
    },
    {
     "id": 1150006784,
     "name": "Arcane Surge",
     "cost": 1600,
     "phase": 0,
     "time": 420.0,
     "p": 0.926,
     "n": 157,
     "builds_into": null,
     "into_keeps_imbue": false,
     "sold_unresolved": false,
     "stat": "+12% Ability Range",
     "imbue": null
    },
    {
     "id": 2951612397,
     "name": "Duration Extender",
     "cost": 1600,
     "phase": 0,
     "time": 527.0,
     "p": 0.711,
     "n": 267,
     "builds_into": "Superior Duration",
     "into_keeps_imbue": false,
     "sold_unresolved": false,
     "stat": "+22% Ability Duration",
     "imbue": {
      "ability": "Pulse Grenade",
      "ability_id": 58655583,
      "share": 0.963,
      "n": 1121,
      "split": false
     }
    },
    {
     "id": 968099481,
     "name": "Extra Spirit",
     "cost": 800,
     "phase": 1,
     "time": 629.0,
     "p": 0.466,
     "n": 84,
     "builds_into": null,
     "into_keeps_imbue": false,
     "sold_unresolved": false,
     "stat": "+10 Spirit Power",
     "imbue": null
    },
    {
     "id": 754480263,
     "name": "Mystic Expansion",
     "cost": 800,
     "phase": 1,
     "time": 731.0,
     "p": 0.795,
     "n": 109,
     "builds_into": "Greater Expansion",
     "into_keeps_imbue": false,
     "sold_unresolved": false,
     "stat": "+20% Ability Range",
     "imbue": {
      "ability": "Pulse Grenade",
      "ability_id": 58655583,
      "share": 0.984,
      "n": 1080,
      "split": false
     }
    },
    {
     "id": 395867183,
     "name": "Mystic Shot",
     "cost": 1600,
     "phase": 1,
     "time": 838.0,
     "p": 0.502,
     "n": 153,
     "builds_into": null,
     "into_keeps_imbue": false,
     "sold_unresolved": false,
     "stat": "+40 Spirit Damage",
     "imbue": null
    },
    {
     "id": 865958998,
     "name": "Veil Walker",
     "cost": 3200,
     "phase": 1,
     "time": 950.0,
     "p": 0.658,
     "n": 25,
     "builds_into": null,
     "into_keeps_imbue": false,
     "sold_unresolved": false,
     "stat": "Invisible",
     "imbue": null
    },
    {
     "id": 876563814,
     "name": "Spirit Lifesteal",
     "cost": 1600,
     "phase": 1,
     "time": 1065.0,
     "p": 0.64,
     "n": 61,
     "builds_into": null,
     "into_keeps_imbue": false,
     "sold_unresolved": false,
     "stat": "+13% Spirit Lifesteal",
     "imbue": null
    },
    {
     "id": 2717651715,
     "name": "Superior Duration",
     "cost": 3200,
     "phase": 1,
     "time": 1194.0,
     "p": 0.018,
     "n": 110,
     "builds_into": null,
     "into_keeps_imbue": false,
     "sold_unresolved": false,
     "stat": "+28% Ability Duration",
     "imbue": null
    },
    {
     "id": 1193964439,
     "name": "Greater Expansion",
     "cost": 3200,
     "phase": 2,
     "time": 1318.0,
     "p": 0.2,
     "n": 443,
     "builds_into": null,
     "into_keeps_imbue": false,
     "sold_unresolved": false,
     "stat": "+30% Ability Range",
     "imbue": null
    },
    {
     "id": 380806748,
     "name": "Compress Cooldown",
     "cost": 1600,
     "phase": 2,
     "time": 1441.0,
     "p": 0.174,
     "n": 60,
     "builds_into": "Superior Cooldown",
     "into_keeps_imbue": false,
     "sold_unresolved": false,
     "stat": "+18% Ability Cooldown Reduction",
     "imbue": {
      "ability": "Pulse Grenade",
      "ability_id": 58655583,
      "share": 0.744,
      "n": 815,
      "split": false
     }
    },
    {
     "id": 630839635,
     "name": "Echo Shard",
     "cost": 6400,
     "phase": 2,
     "time": 1570.0,
     "p": 0.089,
     "n": 348,
     "builds_into": null,
     "into_keeps_imbue": false,
     "sold_unresolved": false,
     "stat": "Reset the cooldown of the imbued non-ultimate ability.",
     "imbue": {
      "ability": "Pulse Grenade",
      "ability_id": 58655583,
      "share": 1.0,
      "n": 1032,
      "split": false
     }
    },
    {
     "id": 3261353684,
     "name": "Superior Cooldown",
     "cost": 3200,
     "phase": 2,
     "time": 1684.0,
     "p": 0.324,
     "n": 30,
     "builds_into": "Transcendent Cooldown",
     "into_keeps_imbue": false,
     "sold_unresolved": false,
     "stat": "+20% Ability Cooldown Reduction",
     "imbue": null
    },
    {
     "id": 915014646,
     "name": "Transcendent Cooldown",
     "cost": 6400,
     "phase": 2,
     "time": 1795.0,
     "p": 0.287,
     "n": 44,
     "builds_into": null,
     "into_keeps_imbue": false,
     "sold_unresolved": false,
     "stat": "+25% Ability Cooldown Reduction",
     "imbue": null
    },
    {
     "id": 2081037738,
     "name": "Mystic Vulnerability",
     "cost": 1600,
     "phase": 3,
     "time": 1910.0,
     "p": 0.128,
     "n": 91,
     "builds_into": null,
     "into_keeps_imbue": false,
     "sold_unresolved": false,
     "stat": "-8% Spirit Resist",
     "imbue": null
    }
   ]
  },
  {
   "hero": "Ivy",
   "hero_id": 20,
   "archetype": "Gun Ivy",
   "share": 0.31448970037453183,
   "win_rate": 0.5284704131001117,
   "n": 2687,
   "items": [
    {
     "id": 1548066885,
     "name": "Extended Magazine",
     "cost": 800,
     "phase": 0,
     "time": 70.0,
     "p": 0.686,
     "n": 2670,
     "builds_into": "Titanic Magazine",
     "into_keeps_imbue": false,
     "sold_unresolved": false,
     "stat": "+30% Max Ammo",
     "imbue": null
    },
    {
     "id": 2356412290,
     "name": "Titanic Magazine",
     "cost": 1600,
     "phase": 0,
     "time": 191.0,
     "p": 0.534,
     "n": 1748,
     "builds_into": null,
     "into_keeps_imbue": false,
     "sold_unresolved": false,
     "stat": "+100% Max Ammo",
     "imbue": null
    },
    {
     "id": 811521119,
     "name": "Tesla Bullets",
     "cost": 3200,
     "phase": 0,
     "time": 304.0,
     "p": 0.802,
     "n": 1135,
     "builds_into": "Capacitor",
     "into_keeps_imbue": false,
     "sold_unresolved": false,
     "stat": "+33 Shock Damage",
     "imbue": null
    },
    {
     "id": 3776945997,
     "name": "Extra Charge",
     "cost": 800,
     "phase": 0,
     "time": 420.0,
     "p": 0.236,
     "n": 388,
     "builds_into": "Rapid Recharge",
     "into_keeps_imbue": false,
     "sold_unresolved": false,
     "stat": "+1 Bonus Ability Charges",
     "imbue": null
    },
    {
     "id": 2603935618,
     "name": "Healbane",
     "cost": 1600,
     "phase": 0,
     "time": 527.0,
     "p": 0.652,
     "n": 19,
     "builds_into": null,
     "into_keeps_imbue": false,
     "sold_unresolved": false,
     "stat": "+7 Spirit Power",
     "imbue": null
    },
    {
     "id": 3403085434,
     "name": "Fleetfoot",
     "cost": 1600,
     "phase": 1,
     "time": 629.0,
     "p": 0.61,
     "n": 122,
     "builds_into": null,
     "into_keeps_imbue": false,
     "sold_unresolved": false,
     "stat": "+3.0mm Move Speed",
     "imbue": null
    },
    {
     "id": 84321454,
     "name": "Quicksilver Reload",
     "cost": 1600,
     "phase": 1,
     "time": 731.0,
     "p": 0.622,
     "n": 81,
     "builds_into": "Mercurial Magnum",
     "into_keeps_imbue": true,
     "sold_unresolved": false,
     "stat": "+44 Damage",
     "imbue": {
      "ability": "Entangling Thorns",
      "ability_id": 4111222521,
      "share": 0.985,
      "n": 596,
      "split": false
     }
    },
    {
     "id": 876563814,
     "name": "Spirit Lifesteal",
     "cost": 1600,
     "phase": 1,
     "time": 838.0,
     "p": 0.553,
     "n": 39,
     "builds_into": null,
     "into_keeps_imbue": false,
     "sold_unresolved": false,
     "stat": "+13% Spirit Lifesteal",
     "imbue": null
    },
    {
     "id": 710436191,
     "name": "Capacitor",
     "cost": 6400,
     "phase": 1,
     "time": 950.0,
     "p": 0.514,
     "n": 97,
     "builds_into": null,
     "into_keeps_imbue": false,
     "sold_unresolved": false,
     "stat": "+5% Fire Rate",
     "imbue": null
    },
    {
     "id": 1672893796,
     "name": "Grit",
     "cost": 800,
     "phase": 1,
     "time": 1065.0,
     "p": 0.213,
     "n": 29,
     "builds_into": "Spirit Shielding",
     "into_keeps_imbue": false,
     "sold_unresolved": false,
     "stat": "+200 Barrier",
     "imbue": null
    },
    {
     "id": 112198670,
     "name": "Spirit Shielding",
     "cost": 1600,
     "phase": 1,
     "time": 1194.0,
     "p": 0.493,
     "n": 33,
     "builds_into": null,
     "into_keeps_imbue": false,
     "sold_unresolved": false,
     "stat": "+300 Barrier",
     "imbue": null
    },
    {
     "id": 787198704,
     "name": "Rapid Recharge",
     "cost": 3200,
     "phase": 2,
     "time": 1318.0,
     "p": 0.266,
     "n": 17,
     "builds_into": null,
     "into_keeps_imbue": false,
     "sold_unresolved": false,
     "stat": "+2 Bonus Ability Charges",
     "imbue": null
    },
    {
     "id": 754480263,
     "name": "Mystic Expansion",
     "cost": 800,
     "phase": 2,
     "time": 1441.0,
     "p": 0.657,
     "n": 285,
     "builds_into": null,
     "into_keeps_imbue": false,
     "sold_unresolved": false,
     "stat": "+20% Ability Range",
     "imbue": {
      "ability": "Entangling Thorns",
      "ability_id": 4111222521,
      "share": 0.63,
      "n": 638,
      "split": false
     }
    },
    {
     "id": 968099481,
     "name": "Extra Spirit",
     "cost": 800,
     "phase": 2,
     "time": 1570.0,
     "p": 0.674,
     "n": 144,
     "builds_into": "Improved Spirit",
     "into_keeps_imbue": false,
     "sold_unresolved": false,
     "stat": "+10 Spirit Power",
     "imbue": null
    },
    {
     "id": 3919289022,
     "name": "Mercurial Magnum",
     "cost": 6400,
     "phase": 2,
     "time": 1684.0,
     "p": 0.753,
     "n": 116,
     "builds_into": null,
     "into_keeps_imbue": false,
     "sold_unresolved": false,
     "stat": "+25% Base Bullet Damage",
     "imbue": {
      "ability": "Entangling Thorns",
      "ability_id": 4111222521,
      "share": 0.984,
      "n": 502,
      "split": false
     }
    },
    {
     "id": 2081037738,
     "name": "Mystic Vulnerability",
     "cost": 1600,
     "phase": 2,
     "time": 1795.0,
     "p": 0.678,
     "n": 64,
     "builds_into": null,
     "into_keeps_imbue": false,
     "sold_unresolved": false,
     "stat": "-8% Spirit Resist",
     "imbue": null
    },
    {
     "id": 7409189,
     "name": "Improved Spirit",
     "cost": 1600,
     "phase": 3,
     "time": 1910.0,
     "p": 0.343,
     "n": 21,
     "builds_into": null,
     "into_keeps_imbue": false,
     "sold_unresolved": false,
     "stat": "+18 Spirit Power",
     "imbue": null
    }
   ]
  }
 ]
};
