#!/usr/bin/env python
"""Test whether the imbue block belongs in the archetype clustering (ADR 0001).

Fits every hero three ways, from the same purchase table in one run:

    families      build family shares alone (the control)
    imbue         the first attempt: target shares, depth, and `has_imbue`
    conditional   target shares only, with non-imbuers at their hero's mean

The first attempt split heroes on whether players bought an imbueable item,
not on what they aimed it at. The 9 imbueable items were the separating item
for 27 of 33 split heroes, and four heroes lost a real split to a 6-11% niche.
So for each hero and fit this reports k and the separating item.

The rule was written down before the results and applied as written. The
conditional block stays only if no hero loses a split it had with build
families alone, and the share of split heroes separated by an imbueable item
falls by at least MATERIAL_DROP. Otherwise imbue is used only for naming and
advice.

    python scripts/compare_imbue_fits.py [--out docs/IMBUE-FIT-COMPARISON.md] [--from-csv]
"""

from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from deadlock import archetype, assets, imbue  # noqa: E402

PURCHASES = Path("data/processed/purchases.parquet")
IMBUES = Path("data/processed/imbues.parquet")
COLUMNS = ["match_id", "player_slot", "hero_id", "item_id"]

# The weight the block would ship at: as much total weight as the families.
IMBUE_WEIGHT = 1.0

# The conditional block's imbueable-item share must be at most this fraction
# of the first attempt's (27 of 33, 82%). Set before the results.
MATERIAL_DROP = 0.5


def hero_rows(
    purchases: pd.DataFrame, blocks: dict[str, pd.DataFrame | None]
) -> list[dict]:
    """One row per hero per fit: k, separation, and the separating item."""
    hero_names = {h: v.name for h, v in assets.load_heroes().items()}
    item_names = {i: it.name for i, it in assets.load_items().items()}
    imbueable = set(imbue.imbueable_items())
    rows = []
    for hero_id, group in purchases.groupby("hero_id"):
        name = hero_names.get(int(hero_id), str(hero_id))
        for fit_name, extra in blocks.items():
            fit = archetype.fit_hero(
                group, hero_id=int(hero_id), hero_name=name, extra=extra
            )
            item_id = gap = None
            if fit.split:
                found = archetype.separating_item(
                    archetype.cluster_prevalence(group, fit.labels)
                )
                if found is not None:
                    item_id, gap = found
            rows.append(
                {
                    "hero_id": int(hero_id),
                    "hero": name,
                    "fit": fit_name,
                    "k": fit.k,
                    "separation": fit.separation if fit.split else float("nan"),
                    "item_id": item_id,
                    "item": item_names.get(item_id, "") if item_id else "",
                    "imbueable": bool(item_id in imbueable) if item_id else False,
                    "gap": gap,
                }
            )
            logging.info(
                "  %-14s %-11s k=%d %s",
                name,
                fit_name,
                fit.k,
                f"on {item_names.get(item_id, item_id)}" if item_id else "",
            )
    return rows


def concentration(table: pd.DataFrame, fit: str) -> tuple[int, int]:
    """(split heroes whose separating item is imbueable, split heroes) for one fit."""
    split = table[(table["fit"] == fit) & (table["k"] > 1)]
    return int(split["imbueable"].sum()), len(split)


def sheet(table: pd.DataFrame, verdict: list[str]) -> str:
    """The comparison sheet as markdown."""
    wide = table.pivot(index="hero", columns="fit", values="k")
    items = table.pivot(index="hero", columns="fit", values="item")
    flags = table.pivot(index="hero", columns="fit", values="imbueable")

    lines = [
        "# Does imbue belong in the archetype clustering?",
        "",
        "Generated by `scripts/compare_imbue_fits.py`. The decision is ADR 0001.",
        "",
        "Three fits of the same purchase table in one run. `families` uses build",
        "family shares alone. `imbue` is the rejected first attempt, which adds",
        "imbue target shares, `has_imbue`, and an imbue count. `conditional`",
        "adds target shares only, with players who imbued nothing placed at",
        "their hero's mean.",
        "",
        "The separating item is the item with the biggest pick-rate gap between",
        "the fit's two least distinct clusters. An asterisk marks one of the",
        "nine imbueable items. `split` is what the conditional block did to the",
        "hero's split compared with build families alone.",
        "",
        "| hero | k families | k imbue | k conditional | split "
        "| separating item (families) | separating item (conditional) |",
        "|---|---|---|---|---|---|---|",
    ]

    def cell(hero: str, fit: str) -> str:
        item = items.loc[hero, fit]
        # No split means no separating item. After a csv round trip that is
        # NaN, not "".
        if pd.isna(item) or not str(item):
            return "--"
        return f"{item} \\*" if flags.loc[hero, fit] else str(item)

    for hero in sorted(wide.index):
        base = int(wide.loc[hero, "families"])
        conditional = int(wide.loc[hero, "conditional"])
        verdict_cell = (
            "gained" if conditional > base
            else "**lost**" if conditional < base
            else "--"
        )
        lines.append(
            f"| {hero} | {base} | {int(wide.loc[hero, 'imbue'])} | {conditional} "
            f"| {verdict_cell} | {cell(hero, 'families')} "
            f"| {cell(hero, 'conditional')} |"
        )

    lines += ["", "## Verdict", ""] + verdict + [""]
    return "\n".join(lines)


def report(table: pd.DataFrame, out: Path) -> None:
    """Apply the rule to the results, write the sheet to `out`, and print the verdict."""
    ks = table.pivot(index="hero", columns="fit", values="k")
    lost = sorted(ks.index[(ks["conditional"] < ks["families"])])
    gained = sorted(ks.index[(ks["conditional"] > ks["families"])])
    lost_vs_imbue = sorted(ks.index[(ks["conditional"] < ks["imbue"])])

    base_hits, base_splits = concentration(table, "families")
    imbue_hits, imbue_splits = concentration(table, "imbue")
    cond_hits, cond_splits = concentration(table, "conditional")
    base_share = base_hits / base_splits if base_splits else 0.0
    imbue_share = imbue_hits / imbue_splits if imbue_splits else 0.0
    cond_share = cond_hits / cond_splits if cond_splits else 0.0

    no_loss = not lost
    dropped = cond_share <= imbue_share * MATERIAL_DROP
    keep = no_loss and dropped

    verdict = [
        f"- Splits gained compared with build families alone: "
        f"{', '.join(gained) if gained else 'none'}",
        f"- Splits **lost** compared with build families alone: "
        f"{', '.join(lost) if lost else 'none'}",
        f"- Splits lost compared with the rejected first attempt: "
        f"{', '.join(lost_vs_imbue) if lost_vs_imbue else 'none'}",
        f"- Separating item is imbueable: {base_hits} of {base_splits} split "
        f"heroes ({base_share:.0%}) with build families alone, "
        f"{imbue_hits} of {imbue_splits} ({imbue_share:.0%}) with the first "
        f"attempt, and {cond_hits} of {cond_splits} ({cond_share:.0%}) with the "
        f"conditional block. The build-family number is the control: it shows "
        f"how often an imbueable item separates a hero's builds without the "
        f"block.",
        "",
        f"**No hero loses a split: {'yes' if no_loss else 'NO'}. "
        f"Share drops by at least half: {'yes' if dropped else 'NO'}.**",
        "",
        (
            "By the rule set before the results, the conditional imbue block "
            "stays in the clustering."
            if keep
            else "By the rule set before the results, imbue stays out of the "
            "clustering and is used only for naming and advice."
        ),
    ]

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(sheet(table, verdict), encoding="utf-8")
    for line in verdict:
        print(line)
    print(f"\nwrote {out}")




def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", default="docs/IMBUE-FIT-COMPARISON.md")
    parser.add_argument(
        "--from-csv",
        action="store_true",
        help="re-render the sheet from the last run's csv instead of refitting",
    )
    args = parser.parse_args()

    logging.basicConfig(
        level=logging.INFO, format="%(asctime)s %(message)s", datefmt="%H:%M:%S"
    )
    out = Path(args.out)
    if args.from_csv:
        # The fit is seeded, so the csv from the last run has the same numbers.
        # This skips refitting 38 heroes three ways.
        table = pd.read_csv(out.with_suffix(".csv"))
        report(table, out)
        return 0

    if not PURCHASES.exists() or not IMBUES.exists():
        logging.error("need %s and %s", PURCHASES, IMBUES)
        return 1

    purchases = pd.read_parquet(PURCHASES, columns=COLUMNS)
    players = archetype.player_index(purchases)
    heroes = archetype.hero_of(purchases)
    imbue_rows = pd.read_parquet(IMBUES)

    blocks = {
        "families": None,
        "imbue": archetype.scale_block(
            imbue.imbue_features(imbue_rows, players=players), IMBUE_WEIGHT
        ),
        "conditional": archetype.scale_block(
            imbue.conditional_features(imbue_rows, players, heroes), IMBUE_WEIGHT
        ),
    }

    table = pd.DataFrame(hero_rows(purchases, blocks))

    table.to_csv(Path(args.out).with_suffix(".csv"), index=False)
    report(table, Path(args.out))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
